### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [nunopress/grav-plugin-metadata_extended#1]
The plugin Metadata Extended can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/metadata_extended`) and click on *Save*, there's the following error:

> **Validation failed:** fields is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, Metadata Extended v1.0.1

**Comment by butchewing** [comment]
+1

Change /user/plugins/metadata_extended/blueprints.yaml to allow the enable toggle switch to work in the admin panel.
```
form:
  validation: strict
  fields:
    enabled:
      type: toggle
      label: PLUGIN_ADMIN.PLUGIN_STATUS
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
```
But that is only part of the solution. Does anyone have the rest of the solution?
